import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yariga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda ea
        voluptatem ipsam enim voluptates quidem animi, quos nemo harum vel?
        Molestias laborum autem error doloremque sunt necessitatibus sit
        nesciunt non.
      </main>
    </>
  );
}
