import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>Yariga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/">Home</Link>
        <Link href="/property">Property list</Link>
        <Link
          href={{
            pathname: "/property/[slug]",
            query: {
              slug: "abc-land",
            },
          }}
        >
          Property list
        </Link>
      </header>
      <main>HomePage</main>
    </>
  );
}
